### ISSUE TITLE
How to protect camera?

### ISSUE THREAD

**Issue by XiangMjjj** [FSavoy/DIY-sky-imager#1]
I really appreciate your manual about DIY-Sky-Imager, it do help me to understand the necessary hardwares about imager system.
However I have a question about camera protetion.For instance,TSI or WSC, their sky imager are equippped with the black band to prevent the sun directly shinning to CCD, but you just capture the sky directly(through a clear glass), making it possible that the CCD of the camera get damaged by sun. Is it a good way that the camera can normally operate for a long time(such as a year or several years)?In a word, I want to know is it possible to picture the sky photo where the sun is in the photo at the same time.
Anyway, thanks for your introduction about diy-sky-imager.

**Comment by FSavoy** [comment]
Hi XiangMjjj,

Thanks a lot for your interest in our work. The question you are rising was
in fact a key decision point in this sky imager project. Our first few sky
imager prototypes used a sun blocker. We removed it in later prototypes.

There are three key considerations here:
- We realized that the sensor damage issue does not happen when we use a
DSLR camera. In DSLR cameras, a mechanical shutter diverts the light to the
viewfinder all the time except during actual image capture. This means that
the sensor is only exposed to the sun light a fraction of the time. In
contrast to this, the sun light is constantly hitting the sensor of
mirror-less cameras, independently of whether an actual image is being
captured. This is the scenario in which sensor damage can happen.
- The dynamic range of the image is much higher when there is no sun
blocker. We mitigate this by capturing 3 images under different exposure
settings. The brightest one captures most details around the sun while
being undersaturated in other areas. The darkest one captures most details
over the horizon while being oversaturated near the sun. A third image acts
as a middle ground. We then compute a HDR image out of these 3 shots.
- We realized that the mechanical part of the shutter is the weakest point
of our design. Due to the very high number of images being captured, the
shutter would usually break after a few months. You might want to refer to
a shutter lifetime database (such as https://shuttercheck.app/data/) to
choose an appropriate camera and estimate the shutter repair cycle.

I hope this clarify your concerns. Please let me know if you have any other
question.

Florian

**Comment by XiangMjjj** [comment]
Dear Florian,

I am VERY GRATEFUL for your detailed explanation and suggestions!It really help me make a sky imager.

I find some researchers(B. Urquhart, Development of a sky imaging system for short-term solar
power forecasting, 2015) used industrial camera(probably no mechanical shutter) with a neutral density(ND) gelatin filter or dome to attenuate sunlight. Although he controled the intensity of the sunlight, the sensor still worked all the time.
Your approach to capture the sky is impressive and is a better way for me.

Thanks a lot
Xiang Mjjj
